name: Update Iron Fish Image

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
      workflow_dispatch: # Allows manual triggering
      
  push:
    branches: [ "main" ]
    
jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull source and target images
      run: |
        SOURCE_IMAGE="ghcr.io/iron-fish/ironfish:latest"
        TARGET_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/iron-fish:latest"

        # Pull the latest source image
        docker pull $SOURCE_IMAGE
        # Try to pull the latest target image
        docker pull $TARGET_IMAGE || echo "Target image not found"

    - name: Push image if it doesn't exist
      run: |
        SOURCE_IMAGE="ghcr.io/iron-fish/ironfish:latest"
        TARGET_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/iron-fish:latest"

        # Get the target image ID
        TARGET_IMAGE_ID=$(docker images $TARGET_IMAGE -q)

        # If target image doesn't exist, push the source image to Docker Hub
        if [ -z "$TARGET_IMAGE_ID" ]; then
          echo "Target image not found, pushing to Docker Hub..."
          docker tag $SOURCE_IMAGE $TARGET_IMAGE
          docker push $TARGET_IMAGE
        fi

    - name: Check for updated image and push if needed
      run: |
        SOURCE_IMAGE="ghcr.io/iron-fish/ironfish:latest"
        TARGET_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/iron-fish:latest"

        # Get the image IDs
        SOURCE_IMAGE_ID=$(docker images $SOURCE_IMAGE -q)
        TARGET_IMAGE_ID=$(docker images $TARGET_IMAGE -q)

        # Check if the image IDs are different
        if [ "$SOURCE_IMAGE_ID" != "$TARGET_IMAGE_ID" ]; then
          echo "Image has changed, updating on Docker Hub..."
          docker tag $SOURCE_IMAGE $TARGET_IMAGE
          docker push $TARGET_IMAGE
        else
          echo "Image has not changed, no update needed."
        fi
