name: Update Iron Fish Image

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
      workflow_dispatch: # Allows manual triggering
      
  push:
    branches: [ "main" ]
    
jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Check for updated image
      run: |
        SOURCE_IMAGE="ghcr.io/iron-fish/ironfish:latest"
        TARGET_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/iron-fish:latest"
        # Push the latest images of Iron Fish
        docker tag ghcr.io/iron-fish/ironfish:latest runonflux/iron-fish:latest
        docker push runonflux/iron-fish:latest
        # Pull the latest images
        docker pull $SOURCE_IMAGE
        docker pull $TARGET_IMAGE
        # Get the image IDs
        SOURCE_IMAGE_ID=$(docker images $SOURCE_IMAGE -q)
        TARGET_IMAGE_ID=$(docker images $TARGET_IMAGE -q)
        # Check if the image IDs are different
        if [ "$SOURCE_IMAGE_ID" != "$TARGET_IMAGE_ID" ]; then
          echo "IMAGE_CHANGED=true" >> $GITHUB_ENV
        else
          echo "IMAGE_CHANGED=false" >> $GITHUB_ENV
        fi
    - name: Update image on Docker Hub
      if: env.IMAGE_CHANGED == 'true'
      run: |
        SOURCE_IMAGE="ghcr.io/iron-fish/ironfish:latest"
        TARGET_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/iron-fish:latest"
        # Tag the new image
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        # Push the new image
        docker push $TARGET_IMAGE
